### ISSUE TITLE
human reconstruction

### ISSUE THREAD

**Issue by erernan** [wmpscc/ipaper.today#10]
标题包含关键词：human reconstruction
摘要包含关键词：dynamic 

另外，能否加入cs.GR分类的文章？目前三维重建等工作通常也属于graphic领域，增加GR分类可以更全面和准确。

**Comment by wmpscc** [comment]
已添加关键词“human reconstruction”，如果匹配不准，可以提供多几篇文章的标题我参考修改。
https://ipaper.today/categories/Human-reconstruction/
