### ISSUE TITLE
point cloud Sampling

### ISSUE THREAD

**Issue by QianLi-cell** [wmpscc/ipaper.today#9]
标题包含关键词：point cloud Sampling
摘要包含关键词：point cloud Sampling

**Comment by QianLi-cell** [comment]
不好意思 可以添加与点云上采样相关的嘛？

**Comment by heidapao2b** [comment]
支持，我也希望添加点云相关的论文

**Comment by wmpscc** [comment]
已添加点云相关论文
https://ipaper.today/categories/%E7%82%B9%E4%BA%91%E7%9B%B8%E5%85%B3/
